routes/web.php
<?php

use Illuminate\Support\Facades\Route;


/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Auth::routes();

Route::namespace('\App\Http\Controllers\Main\\')->group(function () {
    Route::get('/', IndexController::class);
});

// Category Router
    Route::namespace('App\Http\Controllers\Admin\\')->group(function() {

    Route::prefix('admin')->group(function () {

        //Admin Index
        Route::get('/', Main\IndexController::class);

        // Category Route
        Route::prefix('category')->group(function () {
            Route::get('/', Category\IndexController::class)->name('admin.category.index');
            Route::get('/create', Category\CreateController::class)->name('admin.category.create');
            Route::post('/', Category\StoreController::class)->name('admin.category.store');
            Route::get('/{category}', Category\ShowController::class)->name('admin.category.show');
            Route::get('/{category}/edit', Category\EditController::class)->name('admin.category.edit');
            Route::patch('/{category}', Category\UpdateController::class)->name('admin.category.update');
            Route::delete('/{category}', Category\DeleteController::class)->name('admin.category.delete');
        });

        //Tag Route
        Route::prefix('tag')->group(function () {
            Route::get('/', Tag\IndexController::class)->name('admin.tag.index');
            Route::get('/create', Tag\CreateController::class)->name('admin.tag.create');
            Route::post('/', Tag\StoreController::class)->name('admin.tag.store');
            Route::get('/{tag}', Tag\ShowController::class)->name('admin.tag.show');
            Route::get('/{tag}/edit', Tag\EditController::class)->name('admin.tag.edit');
            Route::patch('/{tag}', Tag\UpdateController::class)->name('admin.tag.update');
            Route::delete('/{tag}', Tag\DeleteController::class)->name('admin.tag.delete');
        });

        //Post Route
        Route::prefix('post')->group(function () {
            Route::get('/', Post\IndexController::class)->name('admin.post.index');
            Route::get('/create', Post\CreateController::class)->name('admin.post.create');
            Route::post('/', Post\StoreController::class)->name('admin.post.store');
            Route::get('/{post}', Post\ShowController::class)->name('admin.post.show');
            Route::get('/{post}/edit', Post\EditController::class)->name('admin.post.edit');
            Route::patch('/{post}', Post\UpdateController::class)->name('admin.post.update');
            Route::delete('/{post}', Post\DeleteController::class)->name('admin.post.delete');
        });

        //User Route
        Route::resource('users', User\UserController::class);


    });


});

app/Models/User.php
<?php

namespace App\Models;

use Illuminate\Contracts\Auth\MustVerifyEmail;
use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\SoftDeletes;
use Illuminate\Foundation\Auth\User as Authenticatable;
use Illuminate\Notifications\Notifiable;
use Laravel\Sanctum\HasApiTokens;

class User extends Authenticatable
{
    use HasApiTokens, HasFactory, Notifiable, SoftDeletes;

    const ROLE_ADMIN = 0;
    const ROLE_READER = 1;

    public static function getRoles()
    {
        return [
            self::ROLE_ADMIN => 'Админ',
            self::ROLE_READER => 'Читатель',
        ];

    }

    /**
     * The attributes that are mass assignable.
     *
     * @var array<int, string>
     */
    protected $fillable = [
        'name',
        'email',
        'password',
    ];

    /**
     * The attributes that should be hidden for serialization.
     *
     * @var array<int, string>
     */
    protected $hidden = [
        'password',
        'remember_token',
    ];

    /**
     * The attributes that should be cast.
     *
     * @var array<string, string>
     */
    protected $casts = [
        'email_verified_at' => 'datetime',
    ];
}

app/Http/Controllers/Admin/User/UserController.php
<?php

namespace App\Http\Controllers\Admin\User;

use App\Http\Controllers\Admin\Post\BaseController;
use App\Http\Requests\Admin\User\UpdateRequest;
use App\Models\User;
use App\Http\Requests\Admin\User\StoreRequest;
use Illuminate\Support\Facades\Hash;


class UserController extends BaseController
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $users = User::all();

       return view('admin.user.index', compact('users'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        $roles = User::getRoles();
        return view('admin.user.create', compact('roles'));
    }

    /**
     * Store a newly created resource in storage.
     * @param  \Illuminate\Http\Request  $request
     */
    public function store(StoreRequest $request)
    {
        $data = $request->validated();
        $data['password'] = Hash::make($data['password']);
        User::firstOrCreate(['email' => $data['email']],$data);
       return redirect(route('users.index'));

    }

    /**
     * Display the specified resource.
     * @return \Illuminate\Http\Response
     */
    public function show(User $user)
    {
        return view('admin.user.show',compact('user'));
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function edit(User $user)
    {
        $roles = User::getRoles();

        return view('admin.user.edit', compact('user','roles'));


    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\UpdateRequest  $request
     */
    public function update(UpdateRequest $request, User $user)
    {

        $data = $request->validated();
        $user->update($data);

        return view('admin.user.show', compact('user'));
    }

    /**
     * Remove the specified resource from storage.
     *
     */
    public function destroy(User $user)
    {
        $user->delete();
        return redirect()->route('users.index');
    }
}

resources/views/admin/user/create.blade.php
@extends('admin.layouts.main')
@section('Content Wrapper')
    <!-- Content Wrapper. Contains page content -->
    <div class="content-wrapper">
        <!-- Content Header (Page header) -->
        <div class="content-header">
            <div class="container-fluid">
                <div class="row mb-2">
                    <div class="col-sm-6">
                        <h1 class="m-0">Добавление Пользователя</h1>
                    </div><!-- /.col -->
                    <div class="col-sm-6">
                        <ol class="breadcrumb float-sm-right">
                            <li class="breadcrumb-item"><a href="#">Home</a></li>
                            <li class="breadcrumb-item active">Dashboard v1</li>
                        </ol>
                    </div><!-- /.col -->
                </div><!-- /.row -->
            </div><!-- /.container-fluid -->
        </div>
        <!-- /.content-header -->

        <!-- Main content -->
        <section class="content">
            <div class="container-fluid">
                <!-- Small boxes (Stat box) -->
                <div class="row">

                    <div class="col-12">
    <form action="{{route('users.store')}}" method="post" class="w-50 mt-3">
        @csrf
        <div class="form-group ">
            <label for="name">Введите имя</label>
            <input type="text" class="form-control" id="exampleInputEmail1" aria-describedby="emailHelp" name="name">

        </div>
        <div class="form-group">
            <label for="exampleInputEmail1">Email address</label>
            <input type="email" class="form-control" id="exampleInputEmail1" aria-describedby="emailHelp" name="email">

        </div>
        <div class="form-group">
            <label for="exampleInputPassword1">Password</label>
            <input type="text" class="form-control" id="exampleInputPassword1" name="password">
        </div>

        <div class="form-group">
            <label for="Назначьте роль пользователю"></label>
            <select class="form-control" id="exampleFormControlSelect1" name="role_id">
                @foreach($roles as $id => $role)
                    <option value="{{$id}}" {{$id == old('role_id') ? 'selected' : ''}}>
                        {{$role}}
                    </option>
                @endforeach
            </select>
            @error('role_id')
            <div class="text-danger">{{'Выбкрите роль пользователя'}}</div>
            @enderror
        </div>

        <button type="submit" class="btn btn-secondary">Submit</button>
    </form>
                </div>
            </div>
        </div>
    </section>
    </div>
@endsection

resources/views/admin/user/edit.blade.php
@extends('admin.layouts.main')
@section('Content Wrapper')
<!-- Content Wrapper. Contains page content -->
<div class="content-wrapper">
    <!-- Content Header (Page header) -->
    <div class="content-header">
        <div class="container-fluid">
            <div class="row mb-2">
                <div class="col-sm-6">
                    <h1 class="m-0">Редактирование Пользователя</h1>
                </div><!-- /.col -->
            </div><!-- /.row -->
        </div><!-- /.container-fluid -->
    </div>
    <!-- /.content-header -->

    <!-- Main content -->
    <section class="content">
        <div class="container-fluid">
            <!-- Small boxes (Stat box) -->
            <div class="row">

                <div class="col-12">

                    <form action="{{route('users.update', $user->id)}}" method="post" class="w-50 mt-3">
                        @method('PATCH')
                        @csrf
                        <div class="mb-3">

                            <input type="text" class="form-control" name="name" placeholder="Имя Пользователя" value="{{$user->name}}">
                        </div>

                        @error('name')
                        <div class="text-danger mt-3">
                            Вы не заполнели имя пользователя!
                        </div>
                        @enderror

                        <div class="form-group">
                        <label for="exampleInputEmail1">Email address</label>
                        <input type="email" class="form-control" id="exampleInputEmail1" aria-describedby="emailHelp" name="email" value="{{$user->email}}">

                </div>
                        <div class="form-group">
                            <label for="Назначьте роль пользователю"></label>
                            <select class="form-control" id="exampleFormControlSelect1" name="role_id">
                                @foreach($roles as $id => $role)
                                    <option value="{{$id}}" {{$id == $user->role ? 'selected' : ''}}>
                                        {{$role}}
                                    </option>
                                @endforeach
                            </select>
                            @error('role_id')
                            <div class="text-danger">{{'Выберите роль пользователя'}}</div>
                            @enderror
                        </div>

                        <div class="col-3">
                            <input type="submit" class="btn btn-block btn-secondary"value="Обновить">

                        </div>

                    </form>
                </div>

            </div>

            <!-- /.row -->
        </div><!-- /.container-fluid -->
    </section>
    <!-- /.content -->
</div>
<!-- /.content-wrapper -->
@endsection

resources/views/admin/user/index.blade.php
@extends('admin.layouts.main')
@section('Content Wrapper')
    <!-- Content Wrapper. Contains page content -->
    <div class="content-wrapper">
        <!-- Content Header (Page header) -->
        <div class="content-header">
            <div class="container-fluid">
                <div class="row mb-2">
                    <div class="col-sm-6">
                        <h1 class="m-0">Пользователи</h1>
                    </div><!-- /.col -->
                </div><!-- /.row -->
            </div><!-- /.container-fluid -->
        </div>
        <!-- /.content-header -->

        <!-- Main content -->
        <section class="content">
            <div class="container-fluid">
                <div class="row">
                    {{-- List of category --}}
                    <div class="col-12">
                        <table class="table col-md-6">
                            <thead>
                            <tr>
                                <th scope="col">ID</th>
                                <th scope="col">Name</th>
                                <th scope="col">Created_at</th>
                                <th scope="col">Updated_at</th>
                                <th scope="col" class="text-center" colspan="3">Действие</th>
                            </tr>
                            </thead>
                            <tbody>
                            @foreach($users as $user)
                                <tr>
                                    <td>{{$user->id}}</td>
                                    <td>{{$user->name}}</td>
                                    <td>{{$user->created_at}}</td>
                                    <td>{{$user->updated_at}}</td>
                                    <td><a href="{{route('users.show',$user->id)}}"><i
                                                class="far fa-eye"></i></a></td>
                                    <td><a href="{{route('users.edit', $user->id)}}"><i
                                                class=" text-success fas fa-pencil-alt"></i></a></td>
                                    <td>
                                        <form action="{{route('users.destroy', $user)}}" method="post">
                                            @method('DELETE')
                                            @csrf
                                            <button type="submit" class="border-0 bg-transparent">
                                                <i class= "text-danger fas fa-trash" role="button"></i>
                                            </button>
                                        </form>
                                    </td>


                                </tr>
                            @endforeach

                            </tbody>
                        </table>
                        {{-- End of category list --}}


                    </div>

                    <div class="col-1">
                        <a href="{{route('users.create')}}" type="button" class="btn btn-block btn-secondary">Добавить</a>
                    </div>


                </div>

                <!-- /.row -->
            </div><!-- /.container-fluid -->
        </section>
        <!-- /.content -->
    </div>
    <!-- /.content-wrapper -->
@endsection